DELETE http://localhost:3001/api/persons/6615

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
   "name": "BY",
   "number": "11000"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
   "name": "QQ"
}