### 
GET https://part-3-w5d7.onrender.com/api/persons


DELETE http://localhost:3001/api/persons/2881

###
POST https://part-3-w5d7.onrender.com/api/persons/ HTTP/1.1
Content-Type: application/json

{
   "name": "BY",
   "number": "11000"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
   "name": "Liisa Marttinen",
   "number": "040-243563"
}

###
POST https://part-3-w5d7.onrender.com/api/persons/ HTTP/1.1
Content-Type: application/json

{
   "name": "QQ"
}